cd ~/Documents/MPI/EmergingLanguages/SignSpeechConnieBill/Model/pythonFiles
python modelAnalysis.py 1
python modelAnalysis.py 2
python modelAnalysis.py 3
python modelAnalysis.py 4
python modelAnalysis.py 5
python modelAnalysis.py 6
python modelAnalysis.py 7
python modelAnalysis.py 8
python modelAnalysis.py 9
python modelAnalysis.py 10
python modelAnalysis.py 11
python modelAnalysis.py 12
python modelAnalysis.py 13
python modelAnalysis.py 14
python modelAnalysis.py 1
python modelAnalysis.py 2
python modelAnalysis.py 3
python modelAnalysis.py 4
python modelAnalysis.py 5
python modelAnalysis.py 6
python modelAnalysis.py 7
python modelAnalysis.py 8
python modelAnalysis.py 9
python modelAnalysis.py 10
python modelAnalysis.py 11
python modelAnalysis.py 12
python modelAnalysis.py 13
python modelAnalysis.py 14
python modelAnalysis.py 1
python modelAnalysis.py 2
python modelAnalysis.py 3
python modelAnalysis.py 4
python modelAnalysis.py 5
python modelAnalysis.py 6
python modelAnalysis.py 7
python modelAnalysis.py 8
python modelAnalysis.py 9
python modelAnalysis.py 10
python modelAnalysis.py 11
python modelAnalysis.py 12
python modelAnalysis.py 13
python modelAnalysis.py 14
python modelAnalysis.py 1
python modelAnalysis.py 2
python modelAnalysis.py 3
python modelAnalysis.py 4
python modelAnalysis.py 5
python modelAnalysis.py 6
python modelAnalysis.py 7
python modelAnalysis.py 8
python modelAnalysis.py 9
python modelAnalysis.py 10
python modelAnalysis.py 11
python modelAnalysis.py 12
python modelAnalysis.py 13
python modelAnalysis.py 14
python modelAnalysis.py 1
python modelAnalysis.py 2
python modelAnalysis.py 3
python modelAnalysis.py 4
python modelAnalysis.py 5
python modelAnalysis.py 6
python modelAnalysis.py 7
python modelAnalysis.py 8
python modelAnalysis.py 9
python modelAnalysis.py 10
python modelAnalysis.py 11
python modelAnalysis.py 12
python modelAnalysis.py 13
python modelAnalysis.py 14
python modelAnalysis.py 1
python modelAnalysis.py 2
python modelAnalysis.py 3
python modelAnalysis.py 4
python modelAnalysis.py 5
python modelAnalysis.py 6
python modelAnalysis.py 7
python modelAnalysis.py 8
python modelAnalysis.py 9
python modelAnalysis.py 10
python modelAnalysis.py 11
python modelAnalysis.py 12
python modelAnalysis.py 13
python modelAnalysis.py 14
python modelAnalysis.py 1
python modelAnalysis.py 2
python modelAnalysis.py 3
python modelAnalysis.py 4
python modelAnalysis.py 5
python modelAnalysis.py 6
python modelAnalysis.py 7
python modelAnalysis.py 8
python modelAnalysis.py 9
python modelAnalysis.py 10
python modelAnalysis.py 11
python modelAnalysis.py 12
python modelAnalysis.py 13
python modelAnalysis.py 14
python modelAnalysis.py 1
python modelAnalysis.py 2
python modelAnalysis.py 3
python modelAnalysis.py 4
python modelAnalysis.py 5
python modelAnalysis.py 6
python modelAnalysis.py 7
python modelAnalysis.py 8
python modelAnalysis.py 9
python modelAnalysis.py 10
python modelAnalysis.py 11
python modelAnalysis.py 12
python modelAnalysis.py 13
python modelAnalysis.py 14
python modelAnalysis.py 1
python modelAnalysis.py 2
python modelAnalysis.py 3
python modelAnalysis.py 4
python modelAnalysis.py 5
python modelAnalysis.py 6
python modelAnalysis.py 7
python modelAnalysis.py 8
python modelAnalysis.py 9
python modelAnalysis.py 10
python modelAnalysis.py 11
python modelAnalysis.py 12
python modelAnalysis.py 13
python modelAnalysis.py 14
python modelAnalysis.py 1
python modelAnalysis.py 2
python modelAnalysis.py 3
python modelAnalysis.py 4
python modelAnalysis.py 5
python modelAnalysis.py 6
python modelAnalysis.py 7
python modelAnalysis.py 8
python modelAnalysis.py 9
python modelAnalysis.py 10
python modelAnalysis.py 11
python modelAnalysis.py 12
python modelAnalysis.py 13
python modelAnalysis.py 14
